"""SpurGear — parametric involute spur gear."""

from __future__ import annotations
import math
import cadquery as cq
from .base import Gear

class SpurGear(Gear):
    """Parametric involute spur gear.

    The tooth profile is a true involute generated by unwinding a taut
    string from the base circle.  Between teeth the profile follows the
    root circle; below the base circle a straight radial stub connects the
    root circle to the start of the involute.

    Parameters
    ----------
    module : float
        Gear module (pitch diameter ÷ teeth).  Standard values: 0.5, 1, 1.5,
        2, 2.5, 3, 4, 5 mm.
    teeth : int
        Number of teeth.
    face_width : float
        Axial thickness of the gear body (mm).
    bore : float | None
        Diameter of the central through-bore (mm).  ``None`` = solid hub.
    pressure_angle : float
        Half-angle between the tooth face and the pitch-circle tangent
        (degrees).  Default 20°.
    n_flank : int
        Number of sample points on each involute flank.
    """

    def __init__(
        self,
        module: float,
        teeth: int,
        face_width: float,
        bore: float | None = None,
        pressure_angle: float = 20.0,
        n_flank: int = 32,
    ) -> None:
        super().__init__(module, teeth, face_width, bore, pressure_angle)
        self._n_flank = int(n_flank)
        self._solid = self._build()

    @property
    def solid(self) -> cq.Workplane:
        """The CadQuery solid."""
        return self._solid

    @staticmethod
    def _involute(t: float, r_base: float) -> tuple[float, float]:
        """Raw involute point at roll-angle *t* for base circle *r_base*."""
        return (
            r_base * (math.cos(t) + t * math.sin(t)),
            r_base * (math.sin(t) - t * math.cos(t)),
        )

    @staticmethod
    def _rotate_pt(pt: tuple[float, float], angle: float) -> tuple[float, float]:
        """Rotate 2-D point *pt* CCW by *angle* radians."""
        c, s = math.cos(angle), math.sin(angle)
        x, y = pt
        return (c * x - s * y, s * x + c * y)

    def _gear_profile_points(
        self,
        n_flank: int,
        n_tip: int = 6,
        n_root: int = 6,
    ) -> list[tuple[float, float]]:
        """Return the complete CCW gear cross-section as (x, y) tuples."""
        z   = self.teeth
        phi = math.radians(self.pressure_angle)
        r_b = self.base_radius
        r_a = self.tip_radius
        r_f = self.root_radius

        inv_phi = math.tan(phi) - phi
        t_tip   = math.sqrt((r_a / r_b) ** 2 - 1)
        inv_at_tip = t_tip - math.atan(t_tip)

        pitch_angle    = 2.0 * math.pi / z
        half_base      = math.pi / (2.0 * z) + inv_phi

        if r_f >= r_b:
            t_root = math.sqrt((r_f / r_b) ** 2 - 1)
            use_stub = False
        else:
            t_root    = 0.0
            use_stub  = True

        pts: list[tuple[float, float]] = []

        for i in range(z):
            tc            = i * pitch_angle
            theta_rb      = tc - half_base
            theta_lb      = tc + half_base
            theta_rt      = tc - half_base + inv_at_tip
            theta_lt      = tc + half_base - inv_at_tip
            theta_nr      = tc + pitch_angle - half_base

            if use_stub:
                pts.append((r_f * math.cos(theta_rb), r_f * math.sin(theta_rb)))

            for j in range(n_flank):
                t = t_root + (t_tip - t_root) * j / (n_flank - 1)
                pts.append(self._rotate_pt(self._involute(t, r_b), tc - half_base))

            for j in range(1, n_tip + 1):
                theta = theta_rt + (theta_lt - theta_rt) * j / n_tip
                pts.append((r_a * math.cos(theta), r_a * math.sin(theta)))

            for j in range(1, n_flank):
                t = t_tip - (t_tip - t_root) * j / (n_flank - 1)
                p = self._involute(t, r_b)
                pts.append(self._rotate_pt((p[0], -p[1]), tc + half_base))

            if use_stub:
                pts.append((r_f * math.cos(theta_lb), r_f * math.sin(theta_lb)))

            for j in range(1, n_root):
                theta = theta_lb + (theta_nr - theta_lb) * j / n_root
                pts.append((r_f * math.cos(theta), r_f * math.sin(theta)))

        return pts

    def _build(self) -> cq.Workplane:
        pts = self._gear_profile_points(
            n_flank = self._n_flank,
            n_tip   = max(2, self._n_flank // 8),
            n_root  = max(3, self._n_flank // 8),
        )

        gear = (
            cq.Workplane("XY")
            .polyline(pts)
            .close()
            .extrude(self.face_width)
        )

        if self.bore is not None:
            bore_cyl = (
                cq.Workplane("XY")
                .transformed(offset=cq.Vector(0, 0, -0.1))
                .circle(self.bore / 2.0)
                .extrude(self.face_width + 0.2)
            )
            gear = gear.cut(bore_cyl)

        return gear

if __name__ == "__main__":
    from ocp_vscode import show

    g = SpurGear(module=2, teeth=20, face_width=8, bore=5)

    bb = g.solid.val().BoundingBox()
    print(
        f"SpurGear(m=2, z=20, fw=8, bore=5)\n"
        f"  pitch_r={g.pitch_radius:.3f}  tip_r={g.tip_radius:.3f}  "
        f"root_r={g.root_radius:.3f}  base_r={g.base_radius:.3f}\n"
        f"  bb X=[{bb.xmin:.3f}, {bb.xmax:.3f}]  "
        f"Y=[{bb.ymin:.3f}, {bb.ymax:.3f}]  "
        f"Z=[{bb.zmin:.3f}, {bb.zmax:.3f}]"
    )

    show(g.solid, names=["SpurGear"], colors=["gold"])