#!/usr/bin/env bash
# This file is part of vibe-cading.
#
# vibe-cading is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# vibe-cading is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Seed per-clone .claude/ runtime aliases from canonical content under vibe/.
#
# This project tracks its agent personas and slash-command definitions under
# vibe/agents/ and vibe/commands/.  Claude Code, however, discovers subagents
# and project slash commands at .claude/agents/<name>.md and
# .claude/commands/<name>.md.  Because .claude/ is entirely per-clone scratch
# (see .gitignore), every fresh clone needs runtime aliases populated under
# .claude/ that delegate back to the canonical vibe/ content.
#
# This script writes those aliases.  It only manages aliases whose canonical
# source exists under vibe/; any other files under .claude/ (e.g. personal
# user-level wrappers a maintainer drops in their own clone) are left
# untouched.  Idempotent — safe to run repeatedly.
#
# Usage:
#   vibe_cading/tools/init-claude-runtime.sh           # write the aliases
#   vibe_cading/tools/init-claude-runtime.sh --check   # dry-run; report what would change

set -euo pipefail

# This script lives at <repo-root>/vibe_cading/tools/, so the repo root is two
# directory levels up from the script's own directory (not one).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

DRY_RUN=0
if [[ "${1:-}" == "--check" || "${1:-}" == "-n" ]]; then
  DRY_RUN=1
fi

write_or_diff() {
  local target="$1"
  local content="$2"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    if [[ -f "$target" ]] && diff -q <(printf '%s' "$content") "$target" >/dev/null 2>&1; then
      printf '  unchanged: %s\n' "$target"
    else
      printf '  would write: %s\n' "$target"
    fi
  else
    mkdir -p "$(dirname "$target")"
    printf '%s' "$content" > "$target"
    printf '  wrote: %s\n' "$target"
  fi
}

# Extract the YAML frontmatter (lines between the first two `---` markers,
# inclusive) from a markdown file.  Returns empty string if absent.
extract_frontmatter() {
  awk '
    BEGIN { n = 0 }
    /^---[[:space:]]*$/ {
      n++
      print
      if (n == 2) exit
      next
    }
    n == 1 { print }
  ' "$1"
}

# --- Agent aliases (subagents) -------------------------------------------------

if [[ -d vibe/agents ]]; then
  printf 'Agents:\n'
  for canonical in vibe/agents/*.md; do
    [[ -f "$canonical" ]] || continue
    name="$(basename "$canonical" .md)"
    target=".claude/agents/${name}.md"
    frontmatter="$(extract_frontmatter "$canonical")"
    body=$(cat <<EOF

You are the **${name}** subagent.

The canonical persona definition lives at \`vibe/agents/${name}.md\` (tracked).
This file is a per-clone runtime alias generated by
\`vibe_cading/tools/init-claude-runtime.sh\` — do not hand-edit; edit the canonical instead.

**First action of this session:** read \`vibe/agents/${name}.md\` with the
\`Read\` tool and adopt that persona in full for the remainder of the session.
Treat the user's request that triggered your spawn as the active task.
EOF
    )
    content="${frontmatter}${body}"
    write_or_diff "$target" "$content"
  done
fi

# --- Command aliases (project slash commands) ---------------------------------

if [[ -d vibe/commands ]]; then
  printf 'Commands:\n'
  for canonical in vibe/commands/*.md; do
    [[ -f "$canonical" ]] || continue
    name="$(basename "$canonical" .md)"
    target=".claude/commands/${name}.md"
    frontmatter="$(extract_frontmatter "$canonical")"
    body=$(cat <<EOF

This file is a per-clone runtime alias generated by
\`vibe_cading/tools/init-claude-runtime.sh\` — do not hand-edit; edit the canonical instead.
The canonical command definition lives at
[vibe/commands/${name}.md](../../vibe/commands/${name}.md).

Read that file with the \`Read\` tool and follow its instructions in full,
substituting \`\$ARGUMENTS\` for any \`\$ARGUMENTS\` placeholder it references.
EOF
    )
    content="${frontmatter}${body}"
    write_or_diff "$target" "$content"
  done
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  printf '\n(dry-run) no changes written. Re-run without --check to apply.\n'
else
  printf '\nDone. Aliases under .claude/ now reflect canonical content under vibe/.\n'
fi
