#!/usr/bin/env bash
# This file is part of vibe-cading.
#
# vibe-cading is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# vibe-cading is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Generate docker/.env for docker/compose.yaml.
#
# compose.yaml mounts the project directory at the SAME absolute path inside the
# container as it has on the host ("path identity"). That path depends on where
# you cloned, so it cannot be a committed default — this script detects it and
# writes it to docker/.env (gitignored).
#
# Why path identity: a git worktree's .git file stores an ABSOLUTE `gitdir:`
# pointing into main/.git/worktrees/. Mount the project anywhere else and git
# inside the container cannot resolve any worktree.
#
#   vibe_cading/tools/init-docker-env.sh            # write docker/.env
#   vibe_cading/tools/init-docker-env.sh --force    # overwrite an existing one
#
# Idempotent: refuses to clobber an existing docker/.env unless --force.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/docker/.env"

FORCE=0
[[ "${1:-}" == "--force" || "${1:-}" == "-f" ]] && FORCE=1

# The recommended layout nests the checkout one level below the project
# directory, so stream worktrees can sit beside it as siblings:
#
#   <somewhere>/vibe-cading/main      <- this checkout (stable branch)
#   <somewhere>/vibe-cading/<slug>    <- one worktree per branch, slug == branch
#
# Resolve the layout from git, NOT from this directory's name: when run inside a
# stream worktree the basename is the branch slug, yet the project root is still
# the parent of `main`. `--git-common-dir` points at the ONE real .git (always
# main's, even from a worktree), so its parent is the stable checkout.
GIT_COMMON="$(git -C "$REPO_ROOT" rev-parse --git-common-dir 2>/dev/null || true)"
if [[ -n "$GIT_COMMON" ]]; then
    [[ "$GIT_COMMON" != /* ]] && GIT_COMMON="$REPO_ROOT/$GIT_COMMON"
    MAIN_CHECKOUT="$(cd "$(dirname "$GIT_COMMON")" && pwd)"
else
    # Not a git repo (e.g. a source tarball) — treat this directory as the root.
    MAIN_CHECKOUT="$REPO_ROOT"
fi

if [[ "$(basename "$MAIN_CHECKOUT")" == "main" ]]; then
    LAYOUT="nested"
    VIBE_ROOT="$(dirname "$MAIN_CHECKOUT")"
else
    LAYOUT="flat"
    VIBE_ROOT="$MAIN_CHECKOUT"
fi

if [[ -e "$ENV_FILE" && "$FORCE" -eq 0 ]]; then
    printf 'docker/.env already exists — leaving it alone (re-run with --force to overwrite):\n\n'
    sed 's/^/    /' "$ENV_FILE"
    exit 0
fi

mkdir -p "$REPO_ROOT/docker"
cat > "$ENV_FILE" <<EOF
# Generated by vibe_cading/tools/init-docker-env.sh — safe to edit or delete.
# Gitignored: these paths are specific to this machine.
#
# VIBE_ROOT is mounted at this same absolute path inside the container, so git
# worktree registrations (absolute paths) resolve identically in both contexts.
VIBE_ROOT=$VIBE_ROOT
VIBE_WORKDIR=$REPO_ROOT

# Running several checkouts at once? Give each a distinct project name and
# viewer port, or they contend for the same container and the same host port.
# VIBE_PROJECT=vibe-cading
# VIBE_VIEWER_PORT=3939
EOF

printf 'Wrote %s\n\n' "$ENV_FILE"
sed 's/^/    /' "$ENV_FILE"
printf '\nStart the container with:\n    docker compose -f docker/compose.yaml up -d --build\n'

if [[ "$LAYOUT" == "nested" ]]; then
    printf '\nLayout: nested — sibling worktrees are supported.\n'
    printf 'Add one (slug MUST equal the branch name) with:\n'
    printf '    git -C %s worktree add %s/<branch> <branch>\n' "$REPO_ROOT" "$VIBE_ROOT"
    printf 'It appears inside the running container at the same path; `cd` to it.\n'
    printf 'Remove it with:  git -C %s worktree remove %s/<branch>\n' "$REPO_ROOT" "$VIBE_ROOT"
    printf 'Never run `git worktree prune` — a transient mount gap can make a\n'
    printf 'healthy worktree look stale. Use `git worktree repair <path>`.\n'
else
    printf '\nLayout: flat — this clone cannot host sibling worktrees.\n'
    printf 'That is fine for ordinary use. To enable them later, move this\n'
    printf 'checkout one level down so worktrees can sit beside it:\n\n'
    printf '    mkdir vibe-cading && mv %s vibe-cading/main\n\n' "$(basename "$REPO_ROOT")"
    printf 'then re-run this script with --force.\n'
fi
