# This file is part of vibe-cading.
#
# vibe-cading is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# vibe-cading is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""BevelGear — parametric straight-bevel involute gear via a scaled-section loft.

Construction method (Tredgold approximation — simplified):
----------------------------------------------------------
A true bevel gear uses *spherical involute* (octoid) tooth profiles that vary
continuously along the pitch cone.  This implementation uses the Tredgold
scaled-section loft, which is the accepted method for 3D-printed bevel gears
at FDM tolerances:

1. The heel (large end) toothed cross-section is generated by the shared
   ``Gear.gear_blank_with_teeth_2d`` primitive using the **real tooth count z**
   (not the Tredgold virtual back-cone tooth count ``z_v = z / cos δ``).
   Using the real count (not z_v) is a *further simplification* beyond strict
   back-cone-developed Tredgold — the profile at the heel is a standard
   involute of the actual tooth count, not of the developed back-cone virtual
   gear.  At FDM tolerances this simplification is accepted; at precision
   hobbed-gear tolerances Tredgold's z_v would be required.

2. The toe (small end) profile is the heel profile scaled uniformly about
   (0, 0) by the scale factor ``s = (A_o − face_width) / A_o``.  Because s is
   radius-independent, this uniform scaling preserves the apex-convergence
   invariant: all three cones (root, pitch, tip) converge to the *same*
   on-axis apex at ``Z = R_p / tan δ``.

3. The heel wire at ``Z = 0`` and the toe wire at ``Z = z_toe`` are lofted
   with ``ruled=True`` (straight ruled faces — geometrically correct for cones
   and cheaper than a B-spline skin).

Datum convention:
-----------------
- The flat back/mounting face (heel, large end) sits at ``Z = 0``.
- The gear axis is ``+Z``, pointing from heel toward the apex.
- The pitch circle is centred on ``(0, 0)``.

Design artifact: docs/design_plans/2026-06-26-bevel-gear_design.md
"""

from __future__ import annotations

import math
import warnings

import cadquery as cq

from .base import Gear
from .bore import Bore


class BevelGear(Gear):
    """Parametric straight-bevel involute gear (Tredgold scaled-section loft).

    Inherits from :class:`Gear` and reuses its shared involute 2D primitive
    (:meth:`Gear.gear_blank_with_teeth_2d`) and bore-cutter logic.  The only
    bevel-specific construction is the conical loft: a heel toothed section
    at ``Z = 0`` lofted to a uniformly-scaled toe section at ``Z = _axial_height``
    via :meth:`cq.Solid.makeLoft(..., ruled=True)`.

    **Simplification disclosure (T1 / T2 / R4):**
    The tooth profile is arrayed using the **real tooth count z**, not the
    Tredgold virtual back-cone tooth count ``z_v = z / cos δ``.  This is a
    *further simplification* beyond strict back-cone-developed Tredgold, where
    the planar section would be generated for a virtual gear of z_v teeth.
    The practical difference at FDM print tolerances is negligible; it is
    explicitly called out here so contributors are not misled into thinking the
    implementation is a full Tredgold back-cone derivation.

    Parameters
    ----------
    module : float
        Gear module (pitch diameter ÷ teeth).  Standard values: 0.5, 0.8,
        1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0 mm — see
        ``ISO_STANDARD_MODULES`` and :meth:`Gear.from_iso` for the ISO check.
    teeth : int
        Number of teeth on this gear.  The undercut floor (governed by
        the real tooth count at the base-class level) is conservative-safe
        for bevel gears: since ``z_v = teeth / cos δ ≥ teeth`` always
        (``cos δ ∈ (0, 1)`` for ``0 < δ < 90°``), if the real count clears
        the undercut floor the virtual count clears it by a wider margin.
        The :attr:`virtual_teeth` attribute exposes ``z_v`` for reference.
    mate_teeth : int
        Tooth count of the meshing partner.  Together with ``shaft_angle``,
        this drives the pitch-cone angle ``δ`` via the formula
        ``δ = atan2(sin Σ, (mate_teeth/teeth) + cos Σ)``.
    face_width : float
        Cone-distance span (slant measurement, mm) from heel to toe.
        Must be strictly less than ``outer_cone_distance`` (hard constraint);
        exceeding ``outer_cone_distance / 3`` triggers a ``UserWarning``
        (convention, not enforced).
    bore : float | Bore | None
        Central through-bore.  Pass a plain diameter ``float`` for a round
        bore, or a composable :class:`Bore` instance.  ``None`` = solid hub.
    pressure_angle : float
        Half-angle between the tooth face and the pitch-circle tangent
        (degrees).  Default 20°.
    shaft_angle : float
        Angle Σ (degrees) between the two shaft axes.  Default 90° (the
        dominant RC/Lego right-angle drive case).  Must satisfy
        ``0 < Σ < 180``; 0° and 180° give degenerate parallel/anti-parallel
        cones.
    n_flank : int
        Number of sample points on each involute flank.  Default 32.

    Attributes
    ----------
    pitch_angle : float
        Pitch-cone half-angle δ in **radians**.
        ``δ = atan2(sin Σ, (mate_teeth/teeth) + cos Σ)``
        For a 90° miter pair (z == mate_teeth) δ = π/4 (45°).
    outer_cone_distance : float
        Outer (heel) slant height ``A_o = pitch_radius / sin δ`` (mm).
    pitch_apex_z : float
        ``Z``-coordinate of the pitch apex on the gear axis
        (``A_o · cos δ = pitch_radius / tan δ``).
        Used by :meth:`mesh_with` to pose the coincident-apex bevel pair.
    virtual_teeth : float
        Tredgold virtual (back-cone developed) tooth count
        ``z_v = teeth / cos δ``.  Exposed for reference; the actual profile
        is generated for the *real* tooth count (see simplification disclosure
        above).

    Notes
    -----
    **Datum:** The flat heel/mounting face sits at ``Z = 0``.  The conical
    body tapers into ``+Z`` toward the pitch apex.  The bore axis is ``+Z``.

    **Origin:** ``(0, 0, 0)`` is the centre of the heel face (the gear axis
    intersects the heel plane here).
    """

    def __init__(
        self,
        module: float,
        teeth: int,
        mate_teeth: int,
        face_width: float,
        bore: float | Bore | None = None,
        pressure_angle: float = 20.0,
        shaft_angle: float = 90.0,
        n_flank: int = 32,
    ) -> None:
        # Validate bevel-specific parameters before calling super().__init__
        # so that errors are clear before costly base-class validation.
        mate_teeth = int(mate_teeth)
        if mate_teeth <= 0:
            raise ValueError(
                f"mate_teeth must be a positive integer, got {mate_teeth}"
            )
        shaft_angle = float(shaft_angle)
        if not (0.0 < shaft_angle < 180.0):
            raise ValueError(
                f"shaft_angle must satisfy 0 < Σ < 180°, got {shaft_angle}"
            )

        # Base-class validation: module > 0, face_width > 0, undercut floor,
        # derived radii (pitch_radius, base_radius, tip_radius, root_radius).
        super().__init__(module, teeth, face_width, bore, pressure_angle)

        self.mate_teeth: int = mate_teeth
        self.shaft_angle: float = shaft_angle
        self._n_flank: int = int(n_flank)

        # --- Cone geometry derivation ---
        sigma = math.radians(shaft_angle)
        # Pitch-cone angle δ: general formula valid for any Σ and gear ratio.
        # For Σ=90°, cos Σ=0 and it reduces to atan(teeth/mate_teeth).
        self.pitch_angle: float = math.atan2(
            math.sin(sigma),
            (mate_teeth / self.teeth) + math.cos(sigma),
        )
        delta = self.pitch_angle  # radians; local alias for readability

        # Outer cone distance (slant height from heel to apex along the pitch cone).
        self.outer_cone_distance: float = self.pitch_radius / math.sin(delta)

        # Hard constraint: face_width must be strictly less than outer_cone_distance.
        # At face_width >= A_o the toe scale s = (A_o - fw)/A_o <= 0, which
        # yields a zero-area or inverted toe section — a geometric impossibility.
        if face_width >= self.outer_cone_distance:
            raise ValueError(
                f"face_width={face_width} must be strictly less than "
                f"outer_cone_distance={self.outer_cone_distance:.4f} mm "
                f"(for module={module}, teeth={teeth}, mate_teeth={mate_teeth}, "
                f"shaft_angle={shaft_angle}°). "
                "The cone apex is unreachable with this face width."
            )

        # Soft convention check: exceeding A_o/3 produces a valid but stubby gear.
        if face_width > self.outer_cone_distance / 3.0:
            warnings.warn(
                f"face_width={face_width} exceeds the recommended A_o/3 "
                f"limit ({self.outer_cone_distance / 3.0:.4f} mm). "
                "This produces a valid but stubby bevel gear with a small toe "
                "section. Consider reducing face_width for better strength.",
                UserWarning,
                stacklevel=2,
            )

        # Toe scale factor: uniform radial scale of the heel profile about (0,0).
        # Geometry proof: R_p·s == R_p - z_toe·tan(δ) to 1e-15 (design Round 1).
        self._toe_scale: float = (self.outer_cone_distance - face_width) / self.outer_cone_distance

        # Actual axial height of the lofted body.
        # NOTE: this is NOT face_width (the slant span); it is the projection
        # of the slant onto the Z axis: z_toe = face_width · cos δ.
        # The bore cutter MUST use this value, not face_width (design Round 2).
        self._axial_height: float = face_width * math.cos(delta)

        # Pitch apex on the Z axis; used by mesh_with for the coincident-apex pose.
        self.pitch_apex_z: float = self.pitch_radius / math.tan(delta)

        # Virtual (Tredgold back-cone developed) tooth count for reference.
        # z_v = teeth / cos δ >= teeth always (cos δ < 1 for 0 < δ < 90°).
        # Exposed so contributors understand the conservative-safe undercut floor.
        self.virtual_teeth: float = self.teeth / math.cos(delta)

        # Build the solid and cache it.
        self._solid: cq.Workplane = self._build()

    @property
    def solid(self) -> cq.Workplane:
        """The CadQuery solid representing the generated bevel gear."""
        return self._solid

    def _build(self) -> cq.Workplane:
        """Build the bevel gear solid via a scaled-section ruled loft.

        Pipeline:
        1. Generate the heel toothed 2D profile (real tooth count z).
        2. Scale to obtain the toe profile (uniform scale about (0,0) by s).
        3. Build closed polygon wires at Z=0 (heel) and Z=_axial_height (toe).
        4. Loft with ruled=True (straight ruled faces — correct for cones).
        5. Cut the through-bore (using _axial_height, not face_width — R6).
        6. Assert single solid.
        """
        # Step 1: Heel profile (same primitive SpurGear uses for extrusion).
        heel_pts = Gear.gear_blank_with_teeth_2d(
            module=self.module,
            teeth=self.teeth,
            pressure_angle=self.pressure_angle,
            n_flank=self._n_flank,
        )

        # Step 2: Toe profile — uniformly scale about (0,0).
        # Vertex count and winding are preserved by construction, so
        # ruled=True loft connects vertex-i (heel) to vertex-i (toe) exactly,
        # producing straight-ruled cone faces with no twist.
        s = self._toe_scale
        toe_pts = [(x * s, y * s) for (x, y) in heel_pts]

        # Step 3: Build closed polygon wires at each Z plane.
        # IMPORTANT: cq.Wire.makePolygon defaults close=False (open polyline).
        # We MUST pass close=True for a valid closed section that lofts to a
        # solid rather than an open shell.  (Design Dev-C2.)
        heel_wire = cq.Wire.makePolygon(
            [cq.Vector(x, y, 0.0) for (x, y) in heel_pts],
            close=True,
        )
        toe_wire = cq.Wire.makePolygon(
            [cq.Vector(x, y, self._axial_height) for (x, y) in toe_pts],
            close=True,
        )

        # Step 4: Ruled loft — straight ruled faces (geometrically correct for cones).
        loft_solid = cq.Solid.makeLoft([heel_wire, toe_wire], ruled=True)
        gear = cq.Workplane("XY").add(loft_solid)

        # Step 5: Through-bore.
        # Use self._axial_height (= z_toe = face_width·cosδ), NOT self.face_width.
        # self.face_width is the slant-measured cone-distance span (larger);
        # the actual axial extent of the lofted body is _axial_height.
        # bore_cutter already adds ±overcut at both ends, ensuring clean
        # breakthrough at Z=0 (heel) and Z=_axial_height (toe).
        if self.bore is not None:
            gear = gear.cut(Gear.bore_cutter(self.bore, self._axial_height))

        # Step 6: Topology guard.
        assert len(gear.solids().vals()) == 1, (
            f"BevelGear._build: expected a single contiguous solid, "
            f"got {len(gear.solids().vals())} pieces. "
            "Check the loft wires for open/mismatched profiles."
        )
        return gear

    def mesh_with(
        self,
        other: "Gear",
        phase: float = 0.0,
    ) -> tuple[cq.Workplane, cq.Workplane]:
        """Return ``(self_solid, other_solid)`` posed for bevel-pair visualisation.

        Bevel gears mesh at coincident pitch apexes (not at a center-to-center
        distance like parallel-axis spur/helical gears).  This override builds
        the apex-coincident, Σ-tilted intersecting-axis pose entirely from scratch
        using explicit rotate/translate calls.

        **IMPORTANT — this method does NOT call ``center_distance_to`` or
        ``super().mesh_with``.**  The base ``Gear.mesh_with`` calls
        ``self.center_distance_to(other)``, which encodes a parallel-axis
        center distance ``pitch_radius + other.pitch_radius`` — a concept
        that is geometrically meaningless for intersecting-axis bevel gears
        (and raises ``ValueError`` on cross-module pairs).  The bevel pose
        is defined by coincident apexes and a Σ-tilt, which has no relation
        to that distance.

        Pose construction:
        - ``self`` stays at the origin (heel at ``Z = 0``, apex at
          ``(0, 0, self.pitch_apex_z)``).
        - ``other`` is posed so its apex coincides with self's apex and its
          axis makes angle ``Σ = self.shaft_angle`` with ``+Z``.
          Concretely:
          1. Translate ``other`` so its apex lands on self's apex:
             shift along ``+Z`` by ``self.pitch_apex_z - other_apex_z``.
          2. Apply ``phase`` rotation about ``+Z`` to other (tooth interleave).
          3. Rotate the mate about the apex-anchored ``+X`` axis by
             ``(180° - shaft_angle)`` to tilt it so its axis points at angle Σ
             from ``+Z`` in the canonical XZ plane.

        The resulting pose has both pitch apexes at ``(0, 0, self.pitch_apex_z)``.

        Parameters
        ----------
        other : Gear
            The meshing partner.  Geometrically meaningful only for a
            ``BevelGear`` complement (typically constructed by swapping
            ``teeth`` and ``mate_teeth``).  The signature accepts ``Gear``
            for LSP compatibility, but the apex/Σ pose is bevel-specific.
        phase : float
            Additional phase offset in *degrees* applied to ``other`` as a
            rotation about its own axis before posing.  Default 0.0.

        Returns
        -------
        tuple[cq.Workplane, cq.Workplane]
            ``(self_solid, other_solid)`` posed for preview / assembly.

        Notes
        -----
        This is intended for layout / SVG preview / assembly only; it does
        not drive a motion simulation or represent a kinematically-accurate
        rolling mesh.
        """
        self_solid = self.solid

        # Determine the other gear's apex Z (it may differ from self's).
        if isinstance(other, BevelGear):
            other_apex_z = other.pitch_apex_z
        else:
            # Fallback for a non-BevelGear: treat its apex as being at the
            # top of its face_width (not a geometrically meaningful pose).
            other_apex_z = other.face_width

        # Step 1: Apply tooth-phase rotation to other about +Z at origin.
        # A half-pitch offset (180°/mate_teeth) plus 180° flip makes the mate
        # tooth pocket face self's tooth tip (same convention as the base).
        half_pitch_other_deg = 180.0 / other.teeth
        phase_rot = half_pitch_other_deg + 180.0 + float(phase)

        other_solid = other.solid.rotate((0, 0, 0), (0, 0, 1), phase_rot)

        # Step 2: Translate other so its apex coincides with self's apex.
        # Both apexes must land at (0, 0, self.pitch_apex_z).
        # self's apex is already there by construction.
        # other's apex is currently at (0, 0, other_apex_z) (before tilt).
        # We need: after translation, other's apex is at self.pitch_apex_z.
        # => translate Z by (self.pitch_apex_z - other_apex_z).
        dz = self.pitch_apex_z - other_apex_z
        other_solid = other_solid.translate((0, 0, dz))

        # Step 3: Rotate the mate about the apex point along +X axis
        # by (180° - shaft_angle).
        # Reasoning: other's axis currently points in +Z (same as self's).
        # We want it to point at angle Σ = shaft_angle from +Z.
        # A rotation of (180° - Σ) about the apex-anchored +X axis tilts the
        # axis from +Z to the angle Σ in the XZ plane.
        # For Σ=90°: rotate 90° → mate axis points in +X (canonical right-angle drive).
        # For Σ=45°: rotate 135° → mate axis points at 45° from +Z.
        # ``cq.Workplane.rotate(axisStart, axisEnd, angle)`` defines the
        # rotation axis as the LINE THROUGH TWO POINTS — not a point + a
        # direction vector.  The tilt axis is the +X-direction line *through
        # the apex*, so the end point must share the apex's Z; passing a bare
        # ``(1, 0, 0)`` would define a skew diagonal from the apex down to
        # Z=0 and leave the mate almost coincident with ``self`` (collision).
        apex = (0, 0, self.pitch_apex_z)
        apex_plus_x = (1, 0, self.pitch_apex_z)
        tilt_angle = 180.0 - self.shaft_angle
        other_solid = other_solid.rotate(apex, apex_plus_x, tilt_angle)

        return self_solid, other_solid

    @classmethod
    def demo(cls, **kwargs) -> list[tuple[cq.Workplane, str, str]]:
        """Show a meshing 90° miter bevel pair posed at the shaft angle.

        Constructs a miter pair (module=2, teeth=20/20, face_width=6, bore=5)
        and poses it via :meth:`mesh_with`.  A single-instance ``view.py``
        invocation cannot show the intersecting-axis pose; this demo earns its
        keep by returning both gears at the correct apex-coincident angle.
        """
        g1 = cls(module=2, teeth=20, mate_teeth=20, face_width=6, bore=5)
        g2 = cls(module=2, teeth=20, mate_teeth=20, face_width=6, bore=5)
        self_solid, other_solid = g1.mesh_with(g2)
        return [
            (self_solid, "BevelGear (drive)", "royalblue"),
            (other_solid, "BevelGear (driven)", "gold"),
        ]
