# This file is part of vibe-cading.
#
# vibe-cading is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# vibe-cading is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""SpurGear — parametric involute spur gear.

The involute math, tooth-array construction, and bore-cutter logic are now
``@classmethod`` helpers on :class:`Gear`.  This module is a thin extrusion
of the shared 2D toothed cross-section per Phase 6 §T6.6.
"""

from __future__ import annotations

import cadquery as cq

from .base import Gear
from .bore import Bore


class SpurGear(Gear):
    """Parametric involute spur gear (straight teeth).

    The tooth profile is a true involute generated by unwinding a taut
    string from the base circle.  Between teeth the profile follows the
    root circle; below the base circle a straight radial stub connects the
    root circle to the start of the involute.

    The 2D toothed cross-section is supplied by
    :meth:`Gear.gear_blank_with_teeth_2d` — see :mod:`vibe_cading.mechanical.gears.base`
    for the shared math.  This class only owns the straight extrusion.

    Parameters
    ----------
    module : float
        Gear module (pitch diameter ÷ teeth).  Standard values: 0.5, 0.8,
        1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6.0, 8.0, 10.0 mm — see
        ``ISO_STANDARD_MODULES`` and :meth:`Gear.from_iso` for the ISO
        check.
    teeth : int
        Number of teeth.
    face_width : float
        Axial thickness of the gear body (mm).  The gear extrudes from
        ``Z = 0`` to ``Z = face_width``.
    bore : float | Bore | None
        Central through-bore.  Pass a plain diameter ``float`` for a round
        bore (legacy interface, equivalent to ``RoundBore(diameter=…)``),
        or a composable :class:`Bore` instance (``RoundBore``,
        ``HexBore``, ``DBore``, ``KeyedBore``).  ``None`` = solid hub.
    pressure_angle : float
        Half-angle between the tooth face and the pitch-circle tangent
        (degrees).  Default 20°.
    n_flank : int
        Number of sample points on each involute flank.
    """

    def __init__(
        self,
        module: float,
        teeth: int,
        face_width: float,
        bore: float | Bore | None = None,
        pressure_angle: float = 20.0,
        n_flank: int = 32,
    ) -> None:
        super().__init__(module, teeth, face_width, bore, pressure_angle)
        self._n_flank = int(n_flank)
        self._solid = self._build()

    @property
    def solid(self) -> cq.Workplane:
        """The CadQuery solid."""
        return self._solid

    def _build(self) -> cq.Workplane:
        pts = Gear.gear_blank_with_teeth_2d(
            module=self.module,
            teeth=self.teeth,
            pressure_angle=self.pressure_angle,
            n_flank=self._n_flank,
        )

        gear = (
            cq.Workplane("XY")
            .polyline(pts)
            .close()
            .extrude(self.face_width)
        )

        if self.bore is not None:
            gear = gear.cut(Gear.bore_cutter(self.bore, self.face_width))

        return gear

    @classmethod
    def demo(cls, **kwargs) -> list[tuple[cq.Workplane, str, str]]:
        """Show an m=2, z=20, fw=8, bore=5 spur gear."""
        g = cls(module=2, teeth=20, face_width=8, bore=5)
        return [(g.solid, "SpurGear", "gold")]
