"""SpurGear — parametric involute spur gear.

Parameters
----------
module : float
    Gear module m (mm per tooth).  Pitch diameter = module × teeth.
teeth : int
    Number of teeth.
face_width : float
    Axial length (thickness) of the gear in mm.
bore : float | None
    Through-bore diameter in mm, or None for a solid centre.
pressure_angle : float
    Pressure angle in degrees (default 20°).
n_flank : int
    Number of points sampled along each involute flank (default 32).

Derived read-only attributes
-----------------------------
pitch_radius, base_radius, tip_radius, root_radius : float

Coordinate system
-----------------
Gear centred at XY origin.
Back face at Z = 0, front face at Z = face_width.

Run directly to preview in OCP Viewer::

    python3 models/mechanical/spur_gear.py
"""

from __future__ import annotations

import math
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))

import cadquery as cq


class SpurGear:
    """Parametric involute spur gear.

    The tooth profile is a true involute generated by unwinding a taut
    string from the base circle.  Between teeth the profile follows the
    root circle; below the base circle a straight radial stub connects the
    root circle to the start of the involute.

    Parameters
    ----------
    module : float
        Gear module (pitch diameter ÷ teeth).  Standard values: 0.5, 1, 1.5,
        2, 2.5, 3, 4, 5 mm.
    teeth : int
        Number of teeth.  Must be ≥ ``int(2 / sin²(pressure_angle°))``.
        At 20° that minimum is 17.
    face_width : float
        Axial thickness of the gear body (mm).
    bore : float | None
        Diameter of the central through-bore (mm).  ``None`` = solid hub.
    pressure_angle : float
        Half-angle between the tooth face and the pitch-circle tangent
        (degrees).  Default 20° is the worldwide standard for spur gears.
    n_flank : int
        Number of sample points on each involute flank.  32 gives a smooth
        curve for all practical print resolutions.
    """

    def __init__(
        self,
        module: float,
        teeth: int,
        face_width: float,
        bore: float | None = None,
        pressure_angle: float = 20.0,
        n_flank: int = 32,
    ) -> None:
        # Coerce to correct types (--params CLI passes everything as float)
        teeth   = int(teeth)
        n_flank = int(n_flank)

        if module <= 0:
            raise ValueError(f"module must be positive, got {module}")
        if face_width <= 0:
            raise ValueError(f"face_width must be positive, got {face_width}")

        phi = math.radians(pressure_angle)
        z_min = int(2.0 / math.sin(phi) ** 2)
        if teeth < z_min:
            raise ValueError(
                f"teeth={teeth} would cause undercut; minimum for "
                f"pressure_angle={pressure_angle}° is {z_min}.  "
                "Increase tooth count or use profile shift."
            )

        self.module: float = module
        self.teeth: int = teeth
        self.face_width: float = face_width
        self.bore: float | None = bore
        self.pressure_angle: float = pressure_angle

        # ── Derived radii ──────────────────────────────────────────────────────
        m, z = module, teeth
        self.pitch_radius: float = m * z / 2.0
        self.base_radius: float = self.pitch_radius * math.cos(phi)
        self.tip_radius: float = self.pitch_radius + m          # addendum = m
        self.root_radius: float = self.pitch_radius - 1.25 * m  # dedendum = 1.25 m

        self._n_flank = n_flank
        self._solid = self._build()

    # ── Public API ─────────────────────────────────────────────────────────────

    @property
    def solid(self) -> cq.Workplane:
        """The CadQuery solid."""
        return self._solid

    # ── Low-level geometry helpers ─────────────────────────────────────────────

    @staticmethod
    def _involute(t: float, r_base: float) -> tuple[float, float]:
        """Raw involute point at roll-angle *t* for base circle *r_base*.

        The parametric form is the standard string-unwinding involute::

            x(t) = r_b · (cos t + t·sin t)
            y(t) = r_b · (sin t − t·cos t)

        At t = 0 the point is (r_b, 0).  Radius grows as r_b·√(1 + t²).
        The angle of the point from the origin is (t − arctan t).
        """
        return (
            r_base * (math.cos(t) + t * math.sin(t)),
            r_base * (math.sin(t) - t * math.cos(t)),
        )

    @staticmethod
    def _rotate_pt(pt: tuple[float, float], angle: float) -> tuple[float, float]:
        """Rotate 2-D point *pt* CCW by *angle* radians."""
        c, s = math.cos(angle), math.sin(angle)
        x, y = pt
        return (c * x - s * y, s * x + c * y)

    # ── Profile generation ──────────────────────────────────────────────────────

    def _gear_profile_points(
        self,
        n_flank: int,
        n_tip: int = 6,
        n_root: int = 6,
    ) -> list[tuple[float, float]]:
        """Return the complete CCW gear cross-section as (x, y) tuples.

        The polygon visits, for each tooth in order:
        (a) radial stub from root to base circle  [only when r_f < r_b]
        (b) right involute flank  (base/root → tip)
        (c) tip arc
        (d) left involute flank   (tip → base/root)  [mirror of right]
        (e) radial stub from base to root circle  [only when r_f < r_b]
        (f) root-circle arc to the next tooth

        Consecutive duplicate points are avoided so OCCT does not create
        zero-length edges.
        """
        z   = self.teeth
        phi = math.radians(self.pressure_angle)
        r_b = self.base_radius
        r_a = self.tip_radius
        r_f = self.root_radius

        # ── Scalar gear constants ──────────────────────────────────────────────
        inv_phi = math.tan(phi) - phi                   # involute function at φ
        t_tip   = math.sqrt((r_a / r_b) ** 2 - 1)      # roll angle at tip circle
        inv_at_tip = t_tip - math.atan(t_tip)           # angular offset at tip

        pitch_angle    = 2.0 * math.pi / z
        half_base      = math.pi / (2.0 * z) + inv_phi  # half tooth-angle at base

        # When the base circle is inside the root circle (large z), start the
        # involute directly from the root circle rather than adding a stub.
        if r_f >= r_b:
            t_root = math.sqrt((r_f / r_b) ** 2 - 1)
            use_stub = False
        else:
            t_root    = 0.0
            use_stub  = True

        pts: list[tuple[float, float]] = []

        for i in range(z):
            tc            = i * pitch_angle
            theta_rb      = tc - half_base            # right flank angle at base
            theta_lb      = tc + half_base            # left  flank angle at base
            theta_rt      = tc - half_base + inv_at_tip  # right tip angle
            theta_lt      = tc + half_base - inv_at_tip  # left  tip angle
            theta_nr      = tc + pitch_angle - half_base  # next tooth right base

            # ── (a) Right-side radial stub: root → base ────────────────────────
            if use_stub:
                pts.append((r_f * math.cos(theta_rb), r_f * math.sin(theta_rb)))

            # ── (b) Right involute: t_root → t_tip ────────────────────────────
            # Rotate raw involute by (tc − half_base) so that:
            #   • at t = t_root the point sits at angle theta_rb on r_b (or r_f)
            #   • at t = t_tip  the point sits at angle theta_rt  on r_a
            for j in range(n_flank):
                t = t_root + (t_tip - t_root) * j / (n_flank - 1)
                pts.append(self._rotate_pt(self._involute(t, r_b), tc - half_base))

            # ── (c) Tip arc: theta_rt → theta_lt, skip j=0 (dup of right tip) ─
            # Include j = n_tip so the last arc point equals the left tip exactly.
            for j in range(1, n_tip + 1):
                theta = theta_rt + (theta_lt - theta_rt) * j / n_tip
                pts.append((r_a * math.cos(theta), r_a * math.sin(theta)))

            # ── (d) Left involute (mirrored): t_tip → t_root ──────────────────
            # Mirror the raw involute in x  (negate y), rotate by (tc + half_base).
            # Skip j=0 because that point equals the last tip-arc point.
            for j in range(1, n_flank):
                t = t_tip - (t_tip - t_root) * j / (n_flank - 1)
                p = self._involute(t, r_b)
                pts.append(self._rotate_pt((p[0], -p[1]), tc + half_base))

            # ── (e) Left-side radial stub: base → root ────────────────────────
            if use_stub:
                pts.append((r_f * math.cos(theta_lb), r_f * math.sin(theta_lb)))

            # ── (f) Root arc: left base → next tooth right base ───────────────
            # Skip j=0 (dup of left-root / stub end).
            # j = n_root is the start of the next tooth and will be added there.
            for j in range(1, n_root):
                theta = theta_lb + (theta_nr - theta_lb) * j / n_root
                pts.append((r_f * math.cos(theta), r_f * math.sin(theta)))

        return pts

    # ── Build ───────────────────────────────────────────────────────────────────

    def _build(self) -> cq.Workplane:
        pts = self._gear_profile_points(
            n_flank = self._n_flank,
            n_tip   = max(2, self._n_flank // 8),
            n_root  = max(3, self._n_flank // 8),
        )

        gear = (
            cq.Workplane("XY")
            .polyline(pts)
            .close()
            .extrude(self.face_width)
        )

        if self.bore is not None:
            bore_cyl = (
                cq.Workplane("XY")
                .transformed(offset=cq.Vector(0, 0, -0.1))
                .circle(self.bore / 2.0)
                .extrude(self.face_width + 0.2)
            )
            gear = gear.cut(bore_cyl)

        return gear


# ── Standalone OCP preview ─────────────────────────────────────────────────────

if __name__ == "__main__":
    from ocp_vscode import show

    g = SpurGear(module=2, teeth=20, face_width=8, bore=5)

    bb = g.solid.val().BoundingBox()
    print(
        f"SpurGear(m=2, z=20, fw=8, bore=5)\n"
        f"  pitch_r={g.pitch_radius:.3f}  tip_r={g.tip_radius:.3f}  "
        f"root_r={g.root_radius:.3f}  base_r={g.base_radius:.3f}\n"
        f"  bb X=[{bb.xmin:.3f}, {bb.xmax:.3f}]  "
        f"Y=[{bb.ymin:.3f}, {bb.ymax:.3f}]  "
        f"Z=[{bb.zmin:.3f}, {bb.zmax:.3f}]"
    )

    show(g.solid, names=["SpurGear"], colors=["gold"])
